import "./globals.css";
import type { Metadata } from "next";
import { SUIT } from "@/lib/utils";
import Provider from "@/lib/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={SUIT.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
