import './globals.css';
import type { Metadata } from 'next';
import { SUIT } from '@/lib/utils';
import Provider from '@/lib/Provider';
import { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={SUIT.className}>
        <Provider>{children}</Provider>
        <Toaster position="top-center" />
      </body>
    </html>
  );
};
export default RootLayout;
