# 이 워크플로우는 모든 CI 프로세스의 시작점입니다.
# 여기서 모든 다른 워크플로우가 실행됩니다.
name: CI/CD Pipeline
on:
  workflow_dispatch:
  push:
    branches: ["main", "stg", "dev"]
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - "!.github/workflows/typechecking.yml"
      - "!.github/workflows/build-test.yml"
      - "!.github/workflows/lint.yml"
      - "!.github/workflows/deploy.yml"
      - "**.md"
      - .gitignore
      - ".vscode/**"
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - "!.github/workflows/typechecking.yml"
      - "!.github/workflows/build-test.yml"
      - "!.github/workflows/lint.yml"
      - "!.github/workflows/deploy.yml"
      - "**.md"
      - .gitignore
      - ".vscode/**"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typechecking:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/typechecking.yml
  lint:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/lint.yml
  build-test:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/build-test.yml
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
