# This workflow is the entry point for all CI processes.
# It is from here that all other workflows are launched.
name: CI/CD Pipeline
on:
  workflow_dispatch:
  push:
    branches: ["main", "stg", "dev"]
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - "!.github/workflows/typechecking.yml"
      - "!.github/workflows/build-test.yml"
      - "!.github/workflows/lint.yml"
      - "!.github/workflows/deploy.yml"
      - "**.md"
      - .gitignore
      - ".vscode/**"
  pull_request:
    types: [closed]
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - "!.github/workflows/typechecking.yml"
      - "!.github/workflows/build-test.yml"
      - "!.github/workflows/lint.yml"
      - "!.github/workflows/deploy.yml"
      - "**.md"
      - .gitignore
      - ".vscode/**"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typechecking:
    if: github.event_name == 'push'
    uses: ./.github/workflows/typechecking.yml
  lint:
    if: github.event_name == 'push'
    uses: ./.github/workflows/lint.yml
  deploy:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    uses: ./.github/workflows/deploy.yml
